title: "Xinyan Li's Homepage"
description: "LLM research engineer working on post-training, tool-integrated mathematical reasoning, and efficient inference."
url: "https://saaries.github.io"
baseurl: ""
author: "Xinyan Li"
email: "xinyanli4-c@my.cityu.edu.hk"

markdown: kramdown

google_scholar: "https://scholar.google.com/citations?user=t1HQTIIAAAAJ"
github: "https://github.com/saaries"

footer: yes
template_url: "https://github.com/ankitsultana/researcher/tree/gh-pages"
template_name: "template designed by Ankit Sultana"
footer_text: ""
last_modified_at: "September-2026"

nav:
  - name: "About"
    link: ""
  - name: "Resume"
    link: "resume.pdf"

sass:
  style: expanded
  sass_dir: _sass
